[project]
name = "3-api-de-tareas-simples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.5",
    "fastapi[standard]>=0.139.2",
    "httpx>=0.28.1",
    "httpx2>=2.9.1",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-config>=0.4.0",
    "pyjwt>=2.13.0",
    "pymysql>=1.2.0",
    "pytest>=9.1.1",
    "slowapi>=0.1.10",
    "sqlalchemy>=2.0.51",
]

[tool.fastapi]
entrypoint = "src.main:app"
